language: php

php:
#    - 5.5
    # - 5.6

# sudo: false

# cache:
#   directories:
#     - $HOME/.composer/cache/files

# env:
#   - SYMFONY_VERSION=2.7.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    # - php: 5.6
      # env: SYMFONY_VERSION=3.0.*@dev


before_install:
  - composer self-update
  - composer install --dev --no-interaction
#  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - phpunit
  - phpunit --coverage-text
